# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 652ddc3135b8a7b5b61bef286fee06a52324fe9da927fbe04ec8825fc05eff3bf5df1e06743c291eacec1e322ef738663373227125c1e7091464ec90eacb948f

test:
  secret_key_base: 12bc134f89999f2862084c62db34eb25455d5989af491ca0fc423c8b12b32048d9ca50d2ff354434e47826e8bdc0b5a9f788a2cb890b2d659b3ef75bc6fbcaf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
